{
 "title": "SensorMonitoring",
 "description": "Este dashboard muestra el estado en tiempo real y el histórico de los sensores críticos de la sala de servidores: temperatura, humedad y consumo de energía. Incluye indicadores tipo gauge para los últimos valores medidos y gráficos históricos para analizar tendencias. Los paneles están configurados con thresholds visuales que alertan sobre condiciones fuera de rango, ayudando a prevenir sobrecalentamiento, humedad inadecuada o sobrecarga eléctrica.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Temp",
   "type": "gauge",
   "description": "Muestra la temperatura actual de la sala de servidores según el sensor temperature.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotrds",
     "rawSql": "-- Último valor de temperatura\r\nSELECT decoded_value AS value, timestamp_utc AS time\r\nFROM sensor_data\r\nWHERE sensor_type = 'temperature'\r\nORDER BY timestamp_utc DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Current Hum",
   "type": "gauge",
   "description": "Indica la humedad relativa actual según el sensor humidity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotrds",
     "rawSql": "-- Último valor de temperatura\r\nSELECT decoded_value AS value, timestamp_utc AS time\r\nFROM sensor_data\r\nWHERE sensor_type = 'humidity'\r\nORDER BY timestamp_utc DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Grafica la evolución de la temperatura a lo largo del tiempo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iotrds",
     "rawSql": "-- Histórico de temperatura\r\nSELECT timestamp_utc AS time, decoded_value AS value\r\nFROM sensor_data\r\nWHERE sensor_type = 'temperature'\r\nORDER BY timestamp_utc ASC;\r\n"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "gauge",
   "description": "Muestra el consumo de energía instantáneo medido por el sensor power.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iotrds",
     "rawSql": "-- Último valor de temperatura\r\nSELECT decoded_value AS value, timestamp_utc AS time\r\nFROM sensor_data\r\nWHERE sensor_type = 'power'\r\nORDER BY timestamp_utc DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Evolución del consumo energético a lo largo del tiempo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iotrds",
     "rawSql": "-- Histórico de temperatura\r\nSELECT timestamp_utc AS time, decoded_value AS value\r\nFROM sensor_data\r\nWHERE sensor_type = 'power'\r\nORDER BY timestamp_utc ASC;\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Evolución de la humedad relativa en la sala de servidores.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iotrds",
     "rawSql": "-- Histórico de temperatura\r\nSELECT timestamp_utc AS time, decoded_value AS value\r\nFROM sensor_data\r\nWHERE sensor_type = 'humidity'\r\nORDER BY timestamp_utc ASC;\r\n"
    }
   ]
  }
 ]
}